### ISSUE TITLE
add https skip verify flag

### ISSUE THREAD

**Issue by KleKwi** [six-ddc/plow#10]
can you add https skip verify flag to ignore cert verify，like `-k, --insecure` in curl ?
or is there some way to do this in current version ?

**Comment by chrisoberle** [comment]
The ability to specify a client cert, key, and truststore would also be nice.

**Comment by six-ddc** [comment]
Thanks for your suggestions, I will add these features supporting `--insecure`, `--cert` and `--key` this weekend.

**Comment by six-ddc** [comment]
@KleKwi @chrisoberle hi,  Features --insecure, --cert and --key has beed supported in latest `main` branch. if no problems, I will release it.

**Comment by KleKwi** [comment]
> @KleKwi @chrisoberle hi,  Features --insecure, --cert and --key has beed supported in latest `main` branch. if no problems, I will release it.

Thank you!
