### ISSUE TITLE
can not pull project

### ISSUE THREAD

**Issue by BlackSinny** [six-ddc/plow#12]
when i run go get -u github.com/six-ddc/plow,i got 

```shell
build github.com/six-ddc/plow: cannot load github.com/nicksnyder/go-i18n/i18n: cannot find module providing package github.com/nicksnyder/go-i18n/i18n
```

so i watch  *https://github.com/nicksnyder/go-i18n/*, the pkg catalogue is changed. So

>   github.com/nicksnyder/go-i18n/i18n
>
>  changed
>
> v2/github.com/nicksnyder/go-i18n/i18n

**Comment by six-ddc** [comment]
It's weird. I attempted to run it in Docker and it worked. so which version of go are you using?

```
➜  plow git:(main) docker run --rm -ti golang:1.16-alpine sh
/go # go get -u github.com/six-ddc/plow
go: downloading github.com/six-ddc/plow v1.0.1
go: downloading github.com/go-echarts/go-echarts/v2 v2.2.4
go: downloading github.com/AdhityaRamadhanus/fasthttpcors v0.0.0-20170121111917-d4c07198763a
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/mattn/go-isatty v0.0.13
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/valyala/fasthttp v1.27.0
go: downloading go.uber.org/automaxprocs v1.4.0
go: downloading gopkg.in/alecthomas/kingpin.v3-unstable v3.0.0-20191105091915-95d230a53780
go: downloading github.com/go-echarts/go-echarts v1.0.0
go: downloading golang.org/x/sys v0.0.0-20210514084401-e8d321eab015
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/andybalholm/brotli v1.0.3
go: downloading github.com/klauspost/compress v1.13.0
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/alecthomas/units v0.0.0-20210208195552-ff826a37aa15
go: downloading github.com/nicksnyder/go-i18n v1.10.1
go: downloading golang.org/x/sys v0.0.0-20210616094352-59db8d763f22
go: downloading golang.org/x/net v0.0.0-20210525063256-abc453219eb5
go: downloading golang.org/x/net v0.0.0-20210614182718-04defd469f4e
go: downloading github.com/pelletier/go-toml v1.2.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/klauspost/compress v1.13.1
go: downloading github.com/pelletier/go-toml v1.9.3
/go # plow
plow: error: required argument 'url' not provided, try --help
```

**Comment by BlackSinny** [comment]
> It's weird. I attempted to run it in Docker and it worked. so which version of go are you using?
> 
> ```
> ➜  plow git:(main) docker run --rm -ti golang:1.16-alpine sh
> /go # go get -u github.com/six-ddc/plow
> go: downloading github.com/six-ddc/plow v1.0.1
> go: downloading github.com/go-echarts/go-echarts/v2 v2.2.4
> go: downloading github.com/AdhityaRamadhanus/fasthttpcors v0.0.0-20170121111917-d4c07198763a
> go: downloading github.com/beorn7/perks v1.0.1
> go: downloading github.com/mattn/go-isatty v0.0.13
> go: downloading github.com/mattn/go-runewidth v0.0.13
> go: downloading github.com/valyala/fasthttp v1.27.0
> go: downloading go.uber.org/automaxprocs v1.4.0
> go: downloading gopkg.in/alecthomas/kingpin.v3-unstable v3.0.0-20191105091915-95d230a53780
> go: downloading github.com/go-echarts/go-echarts v1.0.0
> go: downloading golang.org/x/sys v0.0.0-20210514084401-e8d321eab015
> go: downloading github.com/rivo/uniseg v0.2.0
> go: downloading github.com/andybalholm/brotli v1.0.3
> go: downloading github.com/klauspost/compress v1.13.0
> go: downloading github.com/valyala/bytebufferpool v1.0.0
> go: downloading github.com/alecthomas/units v0.0.0-20210208195552-ff826a37aa15
> go: downloading github.com/nicksnyder/go-i18n v1.10.1
> go: downloading golang.org/x/sys v0.0.0-20210616094352-59db8d763f22
> go: downloading golang.org/x/net v0.0.0-20210525063256-abc453219eb5
> go: downloading golang.org/x/net v0.0.0-20210614182718-04defd469f4e
> go: downloading github.com/pelletier/go-toml v1.2.0
> go: downloading gopkg.in/yaml.v2 v2.4.0
> go: downloading golang.org/x/text v0.3.6
> go: downloading github.com/klauspost/compress v1.13.1
> go: downloading github.com/pelletier/go-toml v1.9.3
> /go # plow
> plow: error: required argument 'url' not provided, try --help
> ```

go 1.12.17

**Comment by six-ddc** [comment]
@BlackSinny As the `embed` feature has been used, Please upgrade to version 1.16 and try again.
