### ISSUE TITLE
发送文件压测指令如何编写

### ISSUE THREAD

**Issue by gclm** [six-ddc/plow#21]
### 服务介绍
- 压测服务是个简单的spring boot 文件上传服务
- 预计需要使用from 表单+ multipart/form-data 参数上传，文件参数是file
- 对应的curl: curl http://localhost:8000/predict -F "file=@/Users/gclm/Downloads/064A9498.jpg"  -v
### 我的压测指令
- plow http://localhost:8000/predict -c 20 --body "file=@/Users/gclm/Downloads/064A9498.jpg" -m POST
- plow http://localhost:8000/predict -c 20 --body @/Users/gclm/Downloads/064A9498.jpg -m POST
- plow http://localhost:8000/predict -c 20 --body @/Users/gclm/Downloads/064A9498.jpg -T 'multipart/form-data' -m POST
- plow http://localhost:8000/predict -c 20 --body @/Users/gclm/Downloads/064A9498.jpg -T 'application/json' -m POST

目前我已经使用了上面所有的指令都显示不行，后台根本就无法获取到file对象，所以希望大佬可以指点一下如何编写这个指令，或者能否提供一个curl to plow 的工具呢？

**Comment by six-ddc** [comment]
抱歉目前暂不支持 multipart/form-data 格式的请求，我考虑下怎么支持

**Comment by gclm** [comment]
我看ad 是支持的啊 
```
ab -n 10 -c 6 -p e9ec28e8caac000ae122951b99af9f26.txt -T "multipart/form-data; boundary=----WebKitFormBoundaryAFQSEaLDUcBnvQtT" http://localhost/interface/Resource/upload
```

**Comment by six-ddc** [comment]
> 我看ad 是支持的啊
> 
> ```
> ab -n 10 -c 6 -p e9ec28e8caac000ae122951b99af9f26.txt -T "multipart/form-data; boundary=----WebKitFormBoundaryAFQSEaLDUcBnvQtT" http://localhost/interface/Resource/upload
> ```

ab 这个也只是指定了 header，实际发送的 content 并不是按照 multipart 格式去编码的，而是直接发送的文件内容
你可以试下 ab 去压测你的服务，看看你的服务能不能正常读取到数据
