### ISSUE TITLE
Add support for basic auth

### ISSUE THREAD

**Issue by d-g-t** [six-ddc/plow#87]
Hello!
Would be nice if you added the ability to test the routes protected by basic auth. 
Some of my use cases require this thing, and I have to use ab as a fallback, which is something I don't really want...

**Comment by six-ddc** [comment]
Plow can specify headers using -H, and BasicAuth is actually a type of header format, so it can be manually converted into user:password format using `-H "Authorization: Basic base64(username:password)"`. The base64 calculation part can be done using some online websites such as https://www.debugbear.com/basic-auth-header-generator.

**Comment by d-g-t** [comment]
Well, I know that I can specify just base64 of login:password, but I thought more of options to pass them directly (e.g. -u user -p pass). But thank you anyway for rapid response!
