### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by stloc** [six-ddc/plow#88]
Hi,

On Linux Mint, even after reboot terminal : 

![image](https://github.com/six-ddc/plow/assets/4832070/fe47fbaa-5d3b-4dc5-ab1f-43cf9c66c1be)

**Comment by stloc** [comment]
I will use 
`~ go/bin/plow `

**Comment by six-ddc** [comment]
This is a fairly common issue, you should add $GOPATH/bin to $PATH.
