### ISSUE TITLE
Is possible benchmark a domain web page?

### ISSUE THREAD

**Issue by johnfelipe** [six-ddc/plow#9]

**Comment by six-ddc** [comment]
Eh? What does 'a domain web page' mean?

**Comment by johnfelipe** [comment]
This one
https://foodapphub.dap-udea.co/

**Comment by six-ddc** [comment]
Try this way `plow -c 10 https://foodapphub.dap-udea.co/`.

**Comment by johnfelipe** [comment]
How can view charts like your readme file show?

**Comment by six-ddc** [comment]
`http://127.0.0.1:18888/`

**Comment by johnfelipe** [comment]
is possible view in public ip?

**Comment by six-ddc** [comment]
Try the latest version, it will be default listening on `0.0.0.0:18888`, and you can access it from public ip.

**Comment by johnfelipe** [comment]
Then need to be git pull?
